### PR TITLE
Static Imports and a bit more flexibility

### PR DESCRIPTION
**Pull request by KP64**
This is my first Pull Request.

### CODE REVIEW

**Comment by IceBucle** [comment]
You can add .ico in the image extension

**Comment by IceBucle** [comment]
Your code is very good

**Comment by KP64** [comment]
Thanks :D

**Comment by KP64** [comment]
Does it make sense to push a Type Annotated version of the Project Code? Ive got one ready but idk if it makes sense to push it since python is dynamically typed.

**Comment by IceBucle** [comment]
I don't know. You can commit in differents files (?)

**Pull request merged**
